services:
- dockers
before_install:
- go get github.com/golang/lint/golint
- go get github.com/fzipp/gocyclo
- go get golang.org/x/tools/cmd/goimports
language: go
go:
- 1.8.x
- 1.9.x
script:
- ./.check-fmt.sh
- gocyclo -over 15 .
- goimports -l -e .
- go test -race -v ./...
- go build -v
- ./.docker-create-upload.sh
- ./.build-all-archs.sh
deploy:
  provider: releases
  api_key:
    secure: K2o6tz2pw9OeIqVMu0sO01+9QFXA6GxG90PG3les4FOMqOUxyYZDPorMqlXpmAKD0mJWzP8PuWPSBfT9zSN3FkUHsjKA3mwvpab04rjFGr5ccmm90EfVttFyzAY45fokSA3fJo5T3iGjPbmg8Qtey2ST7X8dmuTt2i2kzv30cE2rmCE2wUfGWmq2r43ygaJBTjYtUCowxkDYsm/86qx0NB9SAD7LRDEWc62bcc0+CJZtRE5XXG4YhDJxDJWgMSEdwPt3i/c4NqYhOGCoLpBAh77mgHLJKf0NaThLa3Z6vVKog4/dBxJGSu+QvqA7jS6S6Pm72wWvcUqSPzL2TMk8zvD2KND9q6RPdTn1MuzvARn+IZOf5ndGgDjilcNgCXuC2adOzuo7rbecmTSkbzgux+RGRixr93p13Vn4Nt/WqLMq2ftqAv/gvmAi3OntShcKv9487zML/tDIxdvXXf7fmJDKl59eBKVddrY1GjzdcNVU8l+UoenrXIJh6+sTKcxLDVoqGb34T9QLWLYEK9bqGcmSHy9MFmjE/vh4vu8K8Fgrcpb/GHruRCqpFWIS2SxQaPawc8zVtBMXOvpnb8839Bi0HtdbInE6FynOUgHQ87UyFgwwB6v5YFAOgSpStpPqVX5O4UWZ2vNI1N83qSnxZfOmiayAA1Z7zlPPZTNq4rY=
  file_glob: true
  file: ftpserver-*
  skip_cleanup: true
  on:
    tags: true
env:
  global:
  - DOCKER_REPO=fclairamb/ftpserver
  - DOCKER_USERNAME=ftpserver
  - secure: oSO/8894LogIINfv341dA69Ugj7MQZJ0qhijQdHJA7uSoOK4566lcbQ6pgYo9aSmmmoJQAYdqTHvmegI9qjboGviPTtaomd/Bg9rhxJ46FzclpES9EhjAhKWwT95lHvvv3uVToNvdu0BrQjJidi2G9mJfgtESHBnMoe3IJYj22Y8hhF6Su252qU+gc4lyVSl8YiIPochhRgR1jF03z+M0UtnsAa33LB8dbtC+ZZeGOrpoJymJ4DOpZH9VeBd9cv0QXCSggGC59zEGrmwuyFCdKNwSO5m86FkqiHWaOj/e5r394B4kLs6wBVzedtQGZSvQoR8JSKae6QQ6COu1Pv8hwQe3yJp48Yv0oDIpNsRcEpTKZW6UF7Nqkxxtxxg7qwEuYFJOfqwGCRGnK80gpl003oFn2u6CY/J5n6yAye96y95TMTfDBOnUp3Euy9pFlV0Qg9jy+vc3ayzJvmWIG8Hv7suO5AkJH0MUL+8LNLjXchDieYh9bb9CuCstELdsWuJkceIgsaOCHhrnY66EOmHIyKXhHHgdSmAWdoOvh2gvo6G1VKy22g6eCiNEquCa80IatN5atRIPtjVMsARYfSZKK3Qx3tBgy0n2k9vv0X/rfHA3PtD1p1x1mXKM3xsdTKYx4dWJDgVw0PbWlgG9j22B5ty8dFatZmcSYCuy8h5ZIk=
